### ISSUE TITLE
local run example is wrong, uses outdated guacamole-with-dependencies jar

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/variant-calling-benchmarks#22]
In the readme this run:

```
vcb-guacamole-local \
    base_config.json \
    infrastructure-configs/local.json \
    guacamole-configs/default.json \
    benchmarks/local-wgs1/benchmark.json \
    --guacamole-jar ~/sinai/git/guacamole/target/guacamole-with-dependencies-0.0.1-SNAPSHOT.jar \
    --out-dir results
```

Is actually using an old guacamole jar from before some pom changes. It should actually take both a guacamole jar and a guacamole deps jar, since these are separate jars now.

**Comment by timodonnell** [comment]
After fixing this issue (so actually using the latest guacamole now locally) now getting this exception:

```
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.version'
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:169)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:505)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
	at org.apache.spark.util.AkkaUtils$.org$apache$spark$util$AkkaUtils$$doCreateActorSystem(AkkaUtils.scala:121)
	at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:53)
	at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:52)
	at org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:1988)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:1979)
	at org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:55)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:266)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:193)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:288)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:457)
	at org.hammerlab.guacamole.commands.SparkCommand.createSparkContext(SparkCommand.scala:65)
	at org.hammerlab.guacamole.commands.SparkCommand.run(SparkCommand.scala:10)
	at org.hammerlab.guacamole.commands.Command.run(Command.scala:46)
	at org.hammerlab.guacamole.Main$.main(Main.scala:68)
	at org.hammerlab.guacamole.Main.main(Main.scala)
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.version'
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:169)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:505)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
	at org.apache.spark.util.AkkaUtils$.org$apache$spark$util$AkkaUtils$$doCreateActorSystem(AkkaUtils.scala:121)
	at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:53)
	at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:52)
	at org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:1988)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:1979)
	at org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:55)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:266)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:193)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:288)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:457)
	at org.hammerlab.guacamole.commands.SparkCommand.createSparkContext(SparkCommand.scala:65)
	at org.hammerlab.guacamole.commands.SparkCommand.run(SparkCommand.scala:10)
	at org.hammerlab.guacamole.commands.Command.run(Command.scala:46)
	at org.hammerlab.guacamole.Main$.main(Main.scala:68)
	at org.hammerlab.guacamole.Main.main(Main.scala)
INFO:root:Deleting: /var/folders/jc/fyrvcrcs3sb8g4mkdg6nl_t80000gp/T/tmp_variant_calling_benchmarks_loci_M8vjOr.txt
Traceback (most recent call last):
  File "/Users/tim/venvs/analysis-venv-2.7/bin/vcb-guacamole-local", line 9, in <module>
    load_entry_point('variant-calling-benchmarks', 'console_scripts', 'vcb-guacamole-local')()
  File "/Users/tim/sinai/git/variant-calling-benchmarks/variant_calling_benchmarks/guacamole_local.py", line 24, in run
    main(args, config)
  File "/Users/tim/sinai/git/variant-calling-benchmarks/variant_calling_benchmarks/guacamole_local.py", line 58, in main
    subprocess.check_call(invocation)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', u'-Xmx4g', u'-XX:MaxPermSize=512m', u'-Dspark.master=local[1]', '-cp', '/Users/tim/sinai/git/guacamole/target/guacamole-0.0.1-SNAPSHOT.jar:/Users/tim/sinai/git/guacamole/target/guacamole-deps-only-0.0.1-SNAPSHOT.jar', 'org.hammerlab.guacamole.Main', 'somatic-joint', u'benchmarks/local-wgs1/recurrence.bam', u'benchmarks/local-wgs1/primary.bam', u'benchmarks/local-wgs1/normal.bam', '--tissue-types', u'tumor', u'tumor', u'normal', '--analytes', u'dna', u'dna', u'dna', '--sample-names', u'recurrence', u'primary', u'normal', '--include-filtered', '--only-somatic', '--loci', u'chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22', '--force-call-loci-file', 'file:///var/folders/jc/fyrvcrcs3sb8g4mkdg6nl_t80000gp/T/tmp_variant_calling_benchmarks_loci_M8vjOr.txt', '--reference-fasta', u'benchmarks/local-wgs1/hg19.partial.fasta', '--reference-fasta-is-partial', '--header-metadata', u'VCB_BENCHMARK=local-wgs1', u'VCB_PATIENT=PT1', '--out', u'results/out.local-wgs1.PT1.vcf']' returned non-zero exit status 1
